### ISSUE TITLE
Steam version is unsupported (black screen on startup, no UI)

### ISSUE THREAD

**Issue by skoki2** [OrfeasZ/ZHMModSDK#16]
After unpacking the mod loader to the retail folder and mods to the mods folder, the game shows black screen when i try to run it.
Im playing on 3.100 steam version.

**Comment by OrfeasZ** [comment]
Unfortunately this is a known issue caused by the Steam Overlay. You could try disabling it and see if that helps.

**Comment by BitKovin** [comment]
Same problem

**Comment by BoraDurgut** [comment]
Yeah have same issue. Maybe, its about amd huh?

**Comment by ToolkitGaming** [comment]
Will this be fixed (if it can)?

**Comment by OrfeasZ** [comment]
I don't have access to the Steam version so I can't do much about it at the moment.
________________________________

**Comment by metaphoria** [comment]
> I don't have access to the Steam version so I can't do much about it at the moment.

There's a free Hitman 3 demo available on Steam, and since it uses the same executable as the full Steam version, this should allow you to troubleshoot any Steam-specific issues without having to purchase anything. It's essentially a free copy of the Steam version, just without any access packs/maps outside of the ICA Facility. 

However, if you already own H2016 and/or H2 on Steam, it'll automatically give you the access packs for those maps as well.

warriorstar-orion's fork of the [ZHM5Randomizer](https://github.com/warriorstar-orion/ZHM5Randomizer) also only supported EGS until recently, but they were able to use the free demo to make it compatible with the Steam version as well.

Thanks so much for all your work on this, by the way. If you're able to look at Steam compatibility via the demo, I know myself and many other Steam users would be extremely grateful.

**Comment by OrfeasZ** [comment]
Thanks for the tip.

Steam is now supported in v1.6.0.

**Comment by metaphoria** [comment]
Thank you! It's now working flawlessly on Steam.
