### ISSUE TITLE
Game getting stuck at startup (unless you use noIntro mod)

### ISSUE THREAD

**Issue by sohaibirfann** [OrfeasZ/ZHMModSDK#27]
4 out of 5 times the game gets stuck at startup

**Comment by OrfeasZ** [comment]
Are you using the correct version of the SDK for your game? Make sure to use version 1.6.0 for the latest update. If you're using any other version then you should update your game and the SDK.

**Comment by sohaibirfann** [comment]
Yep I used that one only and my game is updated to v3.130.0 of EGS. The bug does not occur everytime but it does happen and only way to bypass it is to use the nointro/skipintro mod by enabling it in mods.ini beforehand.

**Comment by OrfeasZ** [comment]
Are there any other mods enabled? If so, maybe one of them is causing this. Otherwise, you could try repairing your game from EGS and seeing if that helps at all. 

If all else fails, try downloading the debug version from the [releases](https://github.com/OrfeasZ/ZHMModSDK/releases) page. When using it, it should pop open a console window next to the game window. See what's the last thing it prints before it gets stuck.

**Comment by OrfeasZ** [comment]
Closing for lack of information. Probably related to #36
