### ISSUE TITLE
Lower FPS while using the SDK

### ISSUE THREAD

**Issue by Yisus89** [OrfeasZ/ZHMModSDK#45]
The SDK unfortunately lowers the framerate by a long shot. In a spot where I'd usually have 106 fps, I now have only 76. So the SDK causes a loss of around 25-30 fps. The SDK is currently a must to use the Freelancer Variations mod. I hope it's possible to fix or attenuate this performance issue.

**Comment by OrfeasZ** [comment]
There is currently an issue related to the UI renderer that is causing a significant performance decrease (up to 50%) that will be fixed in the next update. If you're using the SDK with UI on, then I'd suggest using [this workaround](https://github.com/OrfeasZ/ZHMModSDK/issues/37#issuecomment-1408956191) until then. You will still see a small performance decrease, but it should be in the neighborhood of 5%, not 30%.

**Comment by OrfeasZ** [comment]
@Yisus89 can you try the latest build from [this](https://github.com/OrfeasZ/ZHMModSDK/issues/37#issuecomment-1423222632) comment and see if that improves things for you?

**Comment by Yisus89** [comment]
I have tested the version you linked me and the fps are now back to exactly as they were before. I also enabled the UI again and was able to open it with no issue.
