### ISSUE TITLE
Unable to move 47 even when using the left bumper

### ISSUE THREAD

**Issue by MECHASO** [OrfeasZ/ZHMModSDK#9]
"Keeps camera still while 47 moves" feature doesn't work

**Comment by MECHASO** [comment]
@OrfeasZ

**Comment by Notexe** [comment]
This was an intentional change otherwise 47 would move when you tried moving the camera which was not great.

**Comment by MECHASO** [comment]
I wish there would be a similar feature, thanks for the reply

**Comment by cinbot123** [comment]
@OrfeasZ is there any way to bring this functionality back? it used to work but as @Notexe said, 47 moved no matter what in old versions. unfortunately the update that disabled input that seemingly reenables it with L bumper just disabled input completely instead of doing that. L bumper does freeze the camera, but 47 doesn't budge

**Comment by nick21500** [comment]
@OrfeasZ is there any way to bring this functionality back? it used to work but as @Notexe said, 47 moved no matter what in old versions. unfortunately the update that disabled input that seemingly reenables it with L bumper just disabled input completely instead of doing that. L bumper does freeze the camera, but 47 doesn't budge

**Comment by OrfeasZ** [comment]
Will look into it.

**Comment by OrfeasZ** [comment]
Fixed in [v1.5.0](https://github.com/OrfeasZ/ZHMModSDK/releases/tag/v1.5.0).
